version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd springsecurity-demystification
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p /artifact/scripts
      - cp springsecurity-demystification/target/springsecurity-demystification-0.0.1-SNAPSHOT.jar /artifact/
      - cp appspec.yml /artifact/
      - cp scripts/prepare_services.sh /artifact/scripts
      - scripts/deploy.sh /artifact/scripts
artifacts:
  files:
    - /artifact/springsecurity-demystification-0.0.1-SNAPSHOT.jar
    - /artifact/appspec.yml
    - /artifact/scripts/prepare_services.sh
    - /artifact/scripts/deploy.sh