version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd springsecurity-demystification
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - springsecurity-demystification/target/springsecurity-demystification-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/prepare_services.sh
    - scripts/deploy.sh
  name: artifact-name
  discard-paths: yes
  exclude-paths: excluded paths
  enable-symlinks: no
  s3-prefix: turtle-artifactory
  secondary-artifacts:
    artifactIdentifier:
      files:
        - scripts/prepare_services.sh
        - scripts/deploy.sh
      name: secondary-artifact-name
      discard-paths: no
     artifactIdentifier:
      files:
        - appspec.yml
      discard-paths: yes