version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd springsecurity-demystification
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - springsecurity-demystification-0.0.1-SNAPSHOT.jar
    - application.properties
    - appspec.yml
    - scripts/prepare_services.sh
    - scripts/deploy.sh
  descard-path: no
  base-directory: springsecurity-demystification/target