version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd springsecurity-demystification
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - scripts/prepare_services.sh
    - scripts/deploy.sh
  discard-paths: no
  secondary-artifacts:
    artifactIdentifier:
      files:
        - springsecurity-demystification/target/springsecurity-demystification-0.0.1-SNAPSHOT.jar
      discard-paths: yes